services:

  cotacao-service:
    container_name: servico-cotacao
    image: mostela/desafiocotacoes:latest
    networks:
      - amigoz_desafio_cotacao_network

  app:
    build: .
    container_name: api-desafio-cotacao
    ports:
      - "${API_PORT:-8080}:8080"
    environment:
      - QUOTATION_SERVICE_HOST=http://cotacao-service
      - QUOTATION_SERVICE_PORT=3000
      - LOG_LEVEL=${LOG_LEVEL:-DEBUG}
    depends_on:
      - cotacao-service
    networks:
      - amigoz_desafio_cotacao_network

networks:
  amigoz_desafio_cotacao_network:
    driver: bridge